### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by sach-iyer** [xaviliz/signalGenerator#1]
Amazing work! However, this repository is missing a license. This makes it illegal for users to  to use, modify, or share the software. Could you please add a license, like the [MIT license](https://choosealicense.com/licenses/mit/#suggest-this-license) to this repo to change this? Such a change would be greatly appreciated.

ref: https://choosealicense.com/no-permission/

**Comment by xaviliz** [comment]
Sure, thanks for letting me know :)
